/* Rebuild data/stores.json from a store table (CSV or the Store_Location_Table
 * Excel export saved as CSV). Coordinates are used as-is when present; rows that
 * lack them are geocoded via the U.S. Census (run this where census.gov is
 * reachable — the web session sandbox blocks it, a normal machine does not).
 *
 *   node tools/build-stores.js path/to/stores.csv
 *
 * Recognized columns (case-insensitive): ID_STR/id, DSC_STR/name,
 * ADD_STR/address, LAT_K/lat, LON_K/lon.
 */
const fs = require('fs');
const https = require('https');

const file = process.argv[2];
if (!file) { console.error('usage: node tools/build-stores.js <stores.csv>'); process.exit(1); }

function parseCSV(text) {
  const rows = []; let row = [], cell = '', q = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (q) {
      if (c === '"' && text[i + 1] === '"') { cell += '"'; i++; }
      else if (c === '"') q = false; else cell += c;
    } else if (c === '"') q = true;
    else if (c === ',') { row.push(cell); cell = ''; }
    else if (c === '\n') { row.push(cell); rows.push(row); row = []; cell = ''; }
    else if (c !== '\r') cell += c;
  }
  if (cell !== '' || row.length) { row.push(cell); rows.push(row); }
  return rows.filter((r) => r.some((c) => c.trim() !== ''));
}
function col(headers, names) {
  return headers.findIndex((h) => names.some((n) => h.trim().toLowerCase() === n));
}
function geocode(address) {
  const url = 'https://geocoding.geo.census.gov/geocoder/locations/onelineaddress'
    + `?address=${encodeURIComponent(address)}&benchmark=Public_AR_Current&format=json`;
  return new Promise((res, rej) => {
    https.get(url, (r) => { let d = ''; r.on('data', (c) => (d += c)); r.on('end', () => {
      try { const m = JSON.parse(d).result.addressMatches[0];
        res(m ? { lat: m.coordinates.y, lon: m.coordinates.x } : null); }
      catch (e) { rej(e); } }); }).on('error', rej);
  });
}

(async () => {
  const rows = parseCSV(fs.readFileSync(file, 'utf8'));
  const h = rows[0];
  const ci = {
    id: col(h, ['id_str', 'id', 'store', 'store id']),
    name: col(h, ['dsc_str', 'name', 'store name', 'description']),
    address: col(h, ['add_str', 'address', 'street']),
    lat: col(h, ['lat_k', 'lat', 'latitude']),
    lon: col(h, ['lon_k', 'lon', 'lng', 'longitude']),
  };
  const stores = [];
  for (const r of rows.slice(1)) {
    if (ci.id < 0 || !String(r[ci.id]).trim()) continue;
    let lat = ci.lat >= 0 ? parseFloat(r[ci.lat]) : NaN;
    let lon = ci.lon >= 0 ? parseFloat(r[ci.lon]) : NaN;
    const address = ci.address >= 0 ? String(r[ci.address]).trim() : '';
    if ((!isFinite(lat) || !isFinite(lon)) && address) {
      process.stderr.write(`geocoding #${r[ci.id]} ${address}… `);
      const g = await geocode(address);
      if (g) { lat = g.lat; lon = g.lon; process.stderr.write('ok\n'); }
      else process.stderr.write('NOT FOUND\n');
    }
    stores.push({ id: Number(r[ci.id]) || r[ci.id], name: String(r[ci.name] || '').trim(), address, lat, lon });
  }
  const out = { _note: 'Generated by tools/build-stores.js', source: file, count: stores.length, stores };
  fs.writeFileSync('data/stores.json', JSON.stringify(out, null, 2));
  console.log(`wrote data/stores.json — ${stores.length} stores, ` +
    `${stores.filter((s) => isFinite(s.lat)).length} with coordinates`);
})();
